server:
  port: 7001
spring:
  application:
    name: spring-security
  data:
    mongodb:
      host: localhost
      port: 27017
      database: security_service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    # swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html


